[package]
name = "gamma_daemon"
version = "0.1.0"
edition = "2021"



[profile.release]
opt-level = "s"
lto = true
codegen-units = 1 

[dependencies]
battery = "0.7.8"
bulbb = "0.0.3"
toml = "0.7.3"
serde = {version = "1.0.159", features = ["derive"]}
