[package]
name = "gamma-cli"
description = "CLI for GammaDaemon - changes screen brightness based on notebook battery life"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
readme = "../README.md"
keywords = ["cli", "backlight", "brightness"]

[[bin]]
name = "gd"
path = "src/main.rs"

[dependencies]
gamma-lib = { path = "../lib" }
clap = {workspace = true}
serde_json = {workspace = true}

[dev-dependencies]
tempfile = "3"
