[package]
name = "gamma-daemon"
description = "Daemon for GammaDaemon - changes screen brightness based on notebook battery life"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
readme = "../README.md"
keywords = ["daemon", "backlight", "brightness"]

[lib]
name = "gamma_daemon"
path = "src/lib.rs"

[[bin]]
name = "gamma-daemon"
path = "src/main.rs"

[dependencies]
gamma-lib = { path = "../lib" }
battery = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_json = {workspace = true}
smol = "2.0.2"
async-lock = "3.4.2"
log = "0.4.29"
env_logger = "0.11.10"
blight = "0.7.1"
httparse = "1.10.1"

[dev-dependencies]
gamma-lib = { path = "../lib" }
battery = { workspace = true }
serde_json = { workspace = true }
smol = "2.0.2"
async-lock = "3.4.2"
