name: Rust Code Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  coverage:
    name: Generate and Upload Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install grcov
        run: cargo install grcov

      - name: Build and Test with Coverage
        run: |
          cargo test --no-fail-fast

      - name: Generate lcov.info
        run: |
          grcov . -s . --binary-path ./target/debug/ -t lcov --ignore "/*" -o lcov.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
          # Add your Codecov token as a secret in your repository
          token: ${{ secrets.CODECOV_TOKEN }}
