on:
  pull_request:
  push:
    branches:
      - main

name: Test with Code Coverage

jobs:
  test:
    name: Test
    env:
      PROJECT_NAME_UNDERSCORE: GammaDaemon
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
      RUSTDOCFLAGS: -Cpanic=abort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v3
        with:
          # required for private repositories:
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: true
